Add UserGuide, fix AboutUs image naming convention
AY2122S1-CS2103-F09-2/tp pull request #14
Opened 2021-09-24 02:41 UTC by koh-jx

Add the "Add task" function to the UserGuide, also fixed some issues with the images in AboutUs.java not displaying as intended.

2021-09-24 06:27 UTC, jeffsieu requested changes

2021-09-24 06:27 UTC, jeffsieu commented on docs/team/jeffsieu.md
> +#### [Multivus](https://github.com/wlren/multiverse)
multiverse*

2021-09-24 14:58 UTC, koh-jx commented on docs/team/jeffsieu.md
> +#### [Multivus](https://github.com/wlren/multiverse)
bruh

2021-09-27 08:48 UTC, jeffsieu approved these changes
Is Jonathan's supposed to be empty?

2021-09-27 10:10 UTC, koh-jx commented
> Is Jonathan's supposed to be empty?

Yes, his portfolio hasn't been provided yet.

2021-09-27 10:15 UTC, mingyi456 commented
So I guess we wait a bit more for @yeppog to provide his portfolio before merging?

2021-09-27 17:08 UTC, wlren commented
Merging this, will do up my portfolio and finish up on UserGuide later thi week

2021-09-27 17:08 UTC, merged