Change timestamp UG, format
AY2122S1-CS2103-F09-2/tp pull request #140
Opened 2021-10-30 05:05 UTC by koh-jx

2021-10-30 05:54 UTC, jeffsieu requested changes
I believe the GUI also needs to change to display in `dd-mm-yyyy`

2021-10-30 05:54 UTC, jeffsieu commented on docs/UserGuide.md
> +    - If a parameter is expected only once in the command. If you specified it multiple times,
Remove the first "If"

2021-10-30 06:45 UTC, koh-jx commented
> I believe the GUI also needs to be changed to display in `dd-mm-yyyy`. But that could be done in a different PR.

This is done in the `Timestamp#toString()`

2021-11-02 05:03 UTC, jeffsieu commented
@koh-jx Conflicts need to be resolved.

2021-11-02 09:34 UTC, wlren approved these changes

2021-11-02 09:41 UTC, jeffsieu approved these changes

2021-11-02 09:41 UTC, merged